# Generated by Django 6.1.1 on 2026-09-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mail_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mail',
            unique_together={('key', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='mailrecipient',
            unique_together={('mail', 'recipient')},
        ),
    ]
